[package]
name = "mxw"
authors = ["Ola Næss Kaldestad <mail@okal.no>"]
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/korkje/mxw"
readme = "README.md"
description = """
Cross platform CLI tool for Glorious' Model O/O-/D/D- Wireless.

Reverse engineered using USB packet logs sniffed with
WireShark and USBPcap, as well as decompiled Windows
software (Glorious Core)."""

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
clap_complete = "4.6.7"
hidapi = "2.6.6"
colored = "3.1.1"
